Fixed incompatibility with node v4.7.2
RangeError: Offset + length beyond buffer length
The error was caused by omitting optional parameters that are not optional in node v4.7.2